### ISSUE TITLE
[System Support Request] Dungeon Crawl Classics

### ISSUE THREAD

**Issue by ProgLord** [edzillion/blood-n-guts#118]
More blood is more better. 

Here's the link to Dungeon Crawl Classics

https://github.com/cyface/foundryvtt-dcc

**Comment by ScorchedInk** [comment]
Second this.

**Comment by edzillion** [comment]
This has been added in v0.8.0 (#207) can you test and report back?

**Comment by edzillion** [comment]
Closing as no response.
