### ISSUE TITLE
Please add support for Pathfinder First Edition

### ISSUE THREAD

**Issue by iFloris** [edzillion/blood-n-guts#119]
Hello,

I saw that you added support for pathfinder 2e, would it be possible to also support 1e?
We would love to bleed all over the map 😎

**Comment by Lavaeolous** [comment]
+1

**Comment by ThomasLewis1028** [comment]
+1

**Comment by TabletopsAndAnvils** [comment]
+1 -- Got to experience this module in a 5e game over the holiday and thought it gave a nice addition to the severity of our fights. Would love to add this to our regular pf1e game!

**Comment by marcwagner** [comment]
i would also appreciate pf1 support

**Comment by edzillion** [comment]
This has been added in v0.8.0 (#207) can you test and report back?

**Comment by ThomasLewis1028** [comment]
> This has been added in v0.8.0 (#207) can you test and report back?

Just tested it and it seems to be working with the latest versions o
f both the Pathfinder system and the Blood 'n' Guts module.

![image](https://user-images.githubusercontent.com/14363299/110160927-e7647e80-7da9-11eb-9c76-722c1bd3592f.png)

**Comment by marcwagner** [comment]
its a bit hit and miss for me. It worked in one scene, but then later in another one it did not.

relevant console out put

DisplayObject.ts:657 Uncaught (in promise) TypeError: Cannot read property 'position' of null
    at Token.get (DisplayObject.ts:657)
    at Token.get (DisplayObject.ts:603)
    at SplatToken.<anonymous> (SplatToken.js:385)
    at Generator.next (<anonymous>)
    at SplatToken.js:7
    at new Promise (<anonymous>)
    at __awaiter (SplatToken.js:3)
    at SplatToken.saveState (SplatToken.js:382)
    at SplatToken.updateChanges (SplatToken.js:194)
    at Function.updateTokenOrActorHandler (blood-n-guts.js:160)
get @ DisplayObject.ts:657
get @ DisplayObject.ts:603
(anonymous) @ SplatToken.js:385
(anonymous) @ SplatToken.js:7
__awaiter @ SplatToken.js:3
saveState @ SplatToken.js:382
updateChanges @ SplatToken.js:194
updateTokenOrActorHandler @ blood-n-guts.js:160
(anonymous) @ blood-n-guts.js:432
_call @ foundry.js:2496
callAll @ foundry.js:2456
(anonymous) @ foundry.js:29630
_handleUpdate @ foundry.js:29622
update @ foundry.js:29603
async function (async)
update @ foundry.js:29595
update @ foundry.js:29678
update @ foundry.js:31017
update @ entity.js:642
async function (async)
update @ entity.js:630
TokenHUD._onAttributeUpdate @ canvas.js:195
_onAttributeKeydown @ foundry.js:23256
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
2foundry.js:4503

**Comment by WiNG-CoMM** [comment]
I am also having troubles with foundry v 0.79, B&G v0.8.2 and pf1 0.77.16. Whenever I start painting blood manually, it seems to break the "end of mouse drag" for both painting splats qith the primary mouse button and moving the viewport with the secondary mouse button. The console returns constantly a "Uncaught TypeError: Cannot read property 'pick-up-stix' of undefined" error

**Comment by WiNG-CoMM** [comment]
Further update: the error seems related to some kind of colision with "show drag distance" module. I've disabled it and generally B&G behaves better when selecting splats and so on, no more errors on the console, but I somehow I have lost the ability to draw spats manually. Despite selecting the brush tool, it just paints nothing and I get "blood-n-guts |  updateNonEmbeddedEnties" console messages when I try

**Comment by edzillion** [comment]
thanks for the report @WiNG-CoMM I had a look and it seems the show drag distance module has a mouse handler on all layers, which is going to cause conflicts so I made a PR to their repo to limit it to the token layer here: https://github.com/wsaunders1014/ShowDragDistance/pull/95


🤞

**Comment by edzillion** [comment]
Hmm it seems showDragDistance is not being maintained atm, I quickly tested with drag ruler instead and it worked fine.

https://www.foundryvtt-hub.com/package/drag-ruler/

**Comment by edzillion** [comment]
Going to close this as PF1 seems to be working
