### ISSUE TITLE
Clear Blood Splats via a macro or chat command?

### ISSUE THREAD

**Issue by buttonpushertv** [edzillion/blood-n-guts#124]
I see the ways to clear the blood from a scene (via settings button or tiles icon option). Can there be a method to clear them via a macro as well? Even just a chat command `/blood clear` would be helpful.

Thanks for a cool way to show what everyone is *doing* in combat to each other.

**Comment by edzillion** [comment]
I took your suggestion and in #128 you can write `/blood clear` in chat or in a chat macro and it will wipe splats.

(for GM it will permanently clear them, for PC just until the next update - they should change violence level in settings to disabled to disable fully)
