### ISSUE TITLE
Blood effects not working

### ISSUE THREAD

**Issue by Avitale34** [edzillion/blood-n-guts#125]
I noticed in my game today that if the scene isn't active when a token is dropped on to the map they do not have blood effects. For example I preset up the encounter before bringing my players over to the map they do not bleed. I have tested this a couple times and can be recreated by viewing a scene dropping a token and then activating the scene. Trying it side by side with a token I dropped after activation and that second token works as expected.

**Comment by edzillion** [comment]
That's as expected in the current scope of the module. Since the module does not work on non-active scenes you would have to add those tokens after you have activated it. 

Does this workflow work?
1. Activate scene as GM
2. Add your tokens, set them to bleed
3. Pull the players into the scene.

**Comment by Avitale34** [comment]
Well when I run a lot of sessions and I try to plan most of my sessions well ahead of time and prepare the scene. I pre drag the tokens out into each room to speed up the sessions instead of doing it when the players are waiting for me. Is it possible to add the blood effects to all tokens on the scene when that scene becomes activated? I don't expect blood to work on a non active scene just that the module applies to tokens already on scene. If it's not possible it's okay. Really like the module.

**Comment by edzillion** [comment]
No worries that makes sense. If you tick the box `50% Health = bloodied` it will paint blood splats on tokens when a scene is rendered. I haven't built a proper system for dealing with this situation, but that option will set `healthThreshold` to 50% `damageThreshold` to `0%` and draw splats on tokens that have less than 50% health when the scene is first rendered.

Would that suit your needs? what health threshold do you need?

**Comment by Avitale34** [comment]
Thank you so much, I will try that out in my session today! I think 50% or 75% would be fine.
