### ISSUE TITLE
"Violence Setting" broken

### ISSUE THREAD

**Issue by SoundSherpa** [edzillion/blood-n-guts#130]
Unable to save settings if anything but "disabled" is selected on "violence level". When trying to select a violence level other than disabled, I get the following error in console:

![image](https://user-images.githubusercontent.com/72993376/99712894-4c010500-2a69-11eb-8f5e-965a1b0932c9.png)

More detail:
-This seems to work on another world fine but not on my main world nor on a copy of the main world. 
-Uninstalling and reinstalling the module does not fix the issue unfortunately.
-When I initially changed the settings, it was while testing on an inactive scene. 
-Testing again on another world where it initially worked and it no longer allows me to switch violence levels there either with the same error. On this world, the settings were always changed while on an active scene.

**Comment by edzillion** [comment]
Hey @SoundSherpa the latest build 0.6.9 *should* fix this problem, as I have overhauled the settings system to deal better with this scenario.

**Comment by SoundSherpa** [comment]
Seems to work now! I can now change violence settings and the save button works. Blood splatters as it should thanks!
