### ISSUE TITLE
With Blood N Guts Enabled(v0.6.8), core "Configure Settings" dialog does not close.

### ISSUE THREAD

**Issue by buttonpushertv** [edzillion/blood-n-guts#131]
With only Blood N Guts enabled on FVTT 0.7.7, you cannot click the 'Save' button on the core "Configure Settings" dialog and have it close. In my experiements, you cannot close the window at all. This issue arose after the most recent update to Blood N Guts (v0.6.8).

**Comment by edzillion** [comment]
Ok I know what this is. The mod is not designed to work on non-activated scenes but I am not dealing with settings changes in that situation very well. Will get on it asap, thanks for the report.

**Comment by JLtheking2** [comment]
![Error message](https://user-images.githubusercontent.com/48344299/99824267-77cada80-2b90-11eb-9260-382cd7e9ec69.png)

Yup, I'm new and just installed the mod. Clean 0.7.7 installation and running 5e 1.1.1.  Just tried ticking a box and saving.

**Comment by kriticalkyle** [comment]
I also have the latest version of Foundry, 5e, and the module installed. Verified that there are no conflicts with other modules when experiencing the issue.

**Comment by edzillion** [comment]
Ok all, can you test on latest v0.6.9? Should fix this issue.

**Comment by kriticalkyle** [comment]
Works great for me now, thanks!

**Comment by buttonpushertv** [comment]
Yep, working now for me too. And I like the new "does not work on inactive scenes" message as well.

Thanks.
