### ISSUE TITLE
[feature request] Blood color & other settings configurable outside of editing data files

### ISSUE THREAD

**Issue by SoundSherpa** [edzillion/blood-n-guts#144]
Not sure if possible to configure certain custom settings like race blood color without having to edit the file directly. This will allow users on the Forge cloud service to be able to change these settings as that file access is more difficult when not a local installation.

**Comment by edzillion** [comment]
Thanks for the suggestion. Is it possible to use amazon s3 storage on forge? If so that seems like the obvious solution.

**Comment by SoundSherpa** [comment]
Not sure what you mean. Forge is an online host for Foundry and thus has some of its files inaccessible. I can't find a way to actually download that file to even edit it. I dont think I can use s3 on amazon unfortunately. Wasnt sure if the only way for me  the then edit the file is some sort of interface in the settings. Only world data that I can download is the world.json and this
![image](https://user-images.githubusercontent.com/72993376/99916946-e6b04c80-2cd2-11eb-9c1f-9a9582ec2a68.png)

**Comment by edzillion** [comment]
Will foundry allow loading of resources from outside its own servers? Then the custom files could be hosted on another file host (such as s3 or perhaps dropbox). I had a quick look at their FAQ and their website and couldn't see.

**Comment by SoundSherpa** [comment]
So I did find this:
https://forums.forge-vtt.com/t/how-to-upload-a-modified-version-of-a-module-system/10510

Essentially I can install Foundry and the mod locally, take and edit the .json I want (in this case blood color), then upload that as a totally new module. After that I cant then update it without breaking it and having to do it all over. So it seems possible just not easy to do something like add a creature type.

**Comment by edzillion** [comment]
ok I have this fixed in latest. On forge your custom files are stored in the assets library: https://github.com/edzillion/blood-n-guts#customization

Can you test?

**Comment by SoundSherpa** [comment]
AWESOME. I was able to get this working although my workflow was a little different. 
Forge doesnt allow downloads of files from the asset library. Only rename/delete/move. My workflow:

1. Create copies of the custom.js files from a local install of Foundry (since I could not download them from Forge).
2. Edit the copies of the custom.js to my liking (in this case adding blood for a Kenku player race)
3. Append the leading "custom" to the front of the file names.
4. Delete or rename existing .js files in the Forge asset library.
5. Upload the edited files.
6. Stop/Start the Forge foundry server.
7. Test and it worked!

**Comment by SoundSherpa** [comment]
I think I spoke too soon. I thought my change was taking effect but I after checking some more it actually did not. What I experience is this. If I upload the file as a .js to the asset library and delete the old file, the file will be recreated upon game start and the files I upload are ignored. Alternately if I try to rename the files to .json, I can no longer load Foundry correctly. Not sure if its trying to place that .json and now is unable to but Foundry become completely unusable. I can gather more errors if helpful.

**Comment by edzillion** [comment]
Yeah bad idea editing the file names etc. 

Probably will work if you follow the instructions here: (check *recommended Forge workflow*)

https://github.com/edzillion/blood-n-guts#customization

**Comment by SoundSherpa** [comment]
Individual files cannot be downloaded from the asset library
https://forums.forge-vtt.com/t/feature-request-way-to-download-or-sync-asset-library/11290

I can instead get the files from a local install. After editing them when I reupload, they dont replace the files as the file names are different. This is why I renamed. 

I can edit and upload from a local install of Foundry but the versions of this file from the local foundry install are named differently. If I dont rename as you suggest then there will be 2 of each config file in the data folder.

**Comment by edzillion** [comment]
You can download individual files. Then they will be named right etc.

Go to Assets Library
click on blood-n-guts folder
click on custom.css
then click on the large file icon that you can see on the left with the question mark. 
It will then open the raw file. This is one of mine: https://assets.forge-vtt.com/5fc0339ce6f687dee724d75e/blood-n-guts/custom.css

Then click `save` and save locally. When you edit it then upload to the same place.

**Comment by edzillion** [comment]
If you want to create the files locally that will work too but you are using the wrong files. As stated in the link I sent you:

> These settings files are stored in /Data/blood-n-guts/ (note: this is not inside the modules folder). The files (in JSON format) and the folders will be created for you on install.

**Comment by SoundSherpa** [comment]
Thanks! I think I saw the file as empty and thought that forge wasnt letting me download it correctly. I made changed to blood color of a race and it worked! I think I now fully understand how to configure the settings correctly and your changes allow Forge users to do this. 👍

**Comment by edzillion** [comment]
Great to hear!
