### ISSUE TITLE
[System Request] Requesting Compatibility with Savage Worlds

### ISSUE THREAD

**Issue by brunocalado** [edzillion/blood-n-guts#147]
Hi. This module is great. Thank you.

Can you make it work with Savage Worlds?

The "HP" in SW use this path:
```
Max Wounds: `data.wounds.max`
Current Wounds: `data.wounds.value`
```

0 `Current Wounds` means no damage.
The higher `Current Wounds` more wounded is the Actor.

Thank you.

**Comment by edzillion** [comment]
I had to redesign to deal with ascending damage systems - it's in the latest w/ SWADE support.

Can you test 0.8.4 and report back?

**Comment by brunocalado** [comment]
It's working. Thank you very much.

https://user-images.githubusercontent.com/4999783/110834426-462f6980-827c-11eb-99ee-7e629a7c029e.mp4

**Comment by edzillion** [comment]
nice! thanks for the vid 🙂
