### ISSUE TITLE
Blood color turns black after readding linked token

### ISSUE THREAD

**Issue by Ikabodo** [edzillion/blood-n-guts#152]
If you remove and then add a linked token the blood turns black. It does not seem to happen to unlinked tokens. 

**Steps to reproduce:**
1. Add a token (linked to sheet token)
2. make it bleed. (correct color)
3. heal it.
4. delete it.
5. add it again.
6. make it bleed again. (blood is black)

![image](https://user-images.githubusercontent.com/7766890/100344606-6135e080-2fe1-11eb-96bd-058ecd86de90.png)

**Comment by edzillion** [comment]
Fixed in latest #156 can you test?
