### ISSUE TITLE
0.7.2 causes certain scenes with blood-triggering tokens to never load

### ISSUE THREAD

**Issue by apoapostolov** [edzillion/blood-n-guts#164]
Normal, before Blood and Guts 0.7.2

![image](https://user-images.githubusercontent.com/4083812/100471201-7181b480-30e2-11eb-8caf-c87a6021b36b.png)

With 0.7.2. You cannot unpause the world. Windows never close, only can be minimized. 

![image](https://user-images.githubusercontent.com/4083812/100471147-5747d680-30e2-11eb-9cba-eb0e3d829ba0.png)

**Comment by buttonpushertv** [comment]
It does appear to only be happening on "Activated" scenes. Non-active scenes seems to load properly (since BnG doesn't run on non-active scenes, I guess it's not loading whatever is causing the error on the Active scene.

**Comment by buttonpushertv** [comment]
Reverting to BnG 0.7.1 'corrects' this issue.

**Comment by Th-une** [comment]
Same issue. From 0.7.2, scenes with blood on them are broken

**Comment by Aymeeeric** [comment]
Same thing here!

**Comment by edzillion** [comment]
Fixed in latest. Apologies for the inconvenience.

**Comment by apoapostolov** [comment]
Thank you. All good with 0.7.3
