### ISSUE TITLE
Uncaught (in promise) ReferenceError: ForgeVTT is not defined

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [edzillion/blood-n-guts#165]
My landing scene of my DnD5e World does not work anymore and gives the error below. The scene does not load and everything is the standard background color. I can't see anything and it's unusable. This is a big error and disrupting a possible game. The scene was used to test some BloodNGuts, and possible does not work anymore because of that. Other scenes do work that did not have Blood and Guts on it.

Foundry version: 0.7.7
DnD: 1.1.1
Blood N Guts: Latest version at 27/11/2020

````
settings.js:299 Uncaught (in promise) ReferenceError: ForgeVTT is not defined
    at settings.js:299
    at Generator.next (<anonymous>)
    at settings.js:7
    at new Promise (<anonymous>)
    at __awaiter (settings.js:3)
    at mergeSettingsFiles (settings.js:289)
    at blood-n-guts.js:660
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Game.initialize (foundry.js:6465)
````

**Comment by apoapostolov** [comment]
Same as #164

**Comment by edzillion** [comment]
Fixed in latest. (0.7.3)
