### ISSUE TITLE
[feature request] Add a blood n guts "brush" to Drawing Tools... For staging purposes! :-) 

### ISSUE THREAD

**Issue by Sunamon** [edzillion/blood-n-guts#167]
I Just find I grab a goblin to do this but I thought it might be an easy feature to implement? Also a mop and bucket to to clean some but not all? Kind of an eraser... 

Thanks for all you work on this @edzillion my crew and I are head over heals for **BLOOD n' GUTS**!!!

**Comment by edzillion** [comment]
Hey @Sunamon this took a lot of work but finally I have it (fingers crossed) working, I have made a test version that you can install with this manifest: https://raw.githubusercontent.com/edzillion/blood-n-guts/dev/src/module.json

Give it a try and tell me what you think (it will be added in v0.8.0 if this version is stable)

**Comment by edzillion** [comment]
This has been added in v0.8.0 (#207) can you test and report back?

**Comment by edzillion** [comment]
Going to close this as no reply.
