### ISSUE TITLE
Custom settings blank

### ISSUE THREAD

**Issue by amcvfx** [edzillion/blood-n-guts#168]
Version: 0.7.3

When I change the settings manually and it switches to custom, loading up the Advanced Configuration again gives me blank fields. I am using The Forge (unsure if that changes anything).

![image](https://user-images.githubusercontent.com/35099081/100525362-128e6f00-31b8-11eb-9304-dfb149fca7ee.png)

![image](https://user-images.githubusercontent.com/35099081/100525346-fdb1db80-31b7-11eb-8fdf-ac59c3aabb05.png)

**Comment by edzillion** [comment]
Thanks for the report. Will look into it now.

**Comment by edzillion** [comment]
Fixed in latest (v0.7.4) can you test?

**Comment by amcvfx** [comment]
Seems to be fixed thanks!
