### ISSUE TITLE
toast error and console error on tokens without creature type

### ISSUE THREAD

**Issue by Voldemalort** [edzillion/blood-n-guts#174]
![toast-error](https://user-images.githubusercontent.com/67973071/100958843-b5115f80-34e2-11eb-9666-40d9598dbaf6.png)
![console-error](https://user-images.githubusercontent.com/67973071/100958846-b80c5000-34e2-11eb-9e47-18314a563c7a.png)

**Comment by Voldemalort** [comment]
Try a non npc/pc actor

**Comment by edzillion** [comment]
Thanks for the report. I wonder if that's what's causing canvas drawing failed.

That error should be a warning, but even if it errors it shouldn't crash the canvas.

**Comment by Voldemalort** [comment]
I can try to get you more info later today/tomorrow and see if it's potentially a module conflict.

**Comment by edzillion** [comment]
great if you grab latest (0.7.5) the error will now be a warning, just to clear that up.
