### ISSUE TITLE
Suggestion - Select Token blood colour (radial wheel or slider for individual tokens)

### ISSUE THREAD

**Issue by Bedore27** [edzillion/blood-n-guts#178]
I've been trying for a while to get the custom colours feature to work.  I want one of my players who has a custom race to have pink blood instead of red. We've tried to go through and set a custom colour for her race by saving the files and re uploading as you suggested, it literally broke the game and i had to delete all blood n guts files and re install - It would be really handy if you could select a token and individually set blood colour with a pallet or something. I'd love to see a right click on the token - little blood icon pops up - click on that and have a colour wheel (or slider) pop up - select the colour you want and bam that token has pink blood (or whatever was selected)

**Comment by edzillion** [comment]
You can do this already. Select a Token -> Token Configuration -> Image 

There are 4 options including blood color. Give it a try!

**Comment by Honkou** [comment]
Can you put this information in the readme file? It took me ages to find out!

**Comment by edzillion** [comment]
Sure thing @Honkou it's been a while since I updated it.
