### ISSUE TITLE
Request: Star wars FFG support

### ISSUE THREAD

**Issue by dingbat91** [edzillion/blood-n-guts#179]
Hi there guys, Module looks awesome. Any chance you can get star wars FFG supported?

Thanks for reading!

**Comment by edzillion** [comment]
This has been added in v0.8.0 (#207) can you test and report back?

**Comment by dingbat91** [comment]
The code is working perfectly it's generating blood both from adjustments to character sheet, minion sheet and token value, blood painting also works.

The only issue I've found results from how FFG calculates damage. It's basically inverse to D&D where wounds are counted UP rather than down. So a full health character is 0/max and a character now taking lethal injuries is at max/max. So _technically_ right now the tokens show themselves bleeding out and dying at MAX health rather than none.

Other than that everything is working well for the FFG system!

**Comment by edzillion** [comment]
Ok I didn't realise that. Had to change some things to get ascending damage working.

Can you test latest and report back (0.8.4)?

**Comment by dingbat91** [comment]
Hey there, all appears to be working as expected!
