### ISSUE TITLE
Request: Support for Dark Heresy!

### ISSUE THREAD

**Issue by jayseaseven** [edzillion/blood-n-guts#184]
Hello! 
One system, more than any other, needs this mod: the grimdark wonders of Dark Heresy! I love this mod on our D&D campaign, but it would be perfect to see blood alllllll over the place in DH! Thanks!

**Comment by edzillion** [comment]
Working on this now. So there are no races in DH? Or monster types?

Also what is 'critical damage'?

**Comment by jayseaseven** [comment]
There are races: human, Ork, Tau, Eldar, daemon--of course many different monster-types which could leave room for color variation. Critical damage includes any wounds taken below 0.

**Comment by edzillion** [comment]
This has been added in latest version v0.8.0 (#207)

**Comment by edzillion** [comment]
Closing as no response.
