### ISSUE TITLE
Request: Support for Twodsix Cepheus & Traveller (unofficial)

### ISSUE THREAD

**Issue by xdy** [edzillion/blood-n-guts#185]
I.e. https://github.com/xdy/twodsix-foundryvtt
The HP-equivalent can be found in data.hits.{value,max,min}, which is actually the sum of the three physical characteristics.
It currently only populates when one of the base characteristics takes damage. (I.e. to populate it, edit one of the 'damage' (red) fields on the character sheets characteristics section to the left.)
E.g.:
![image](https://user-images.githubusercontent.com/246024/101532503-f26b6680-3994-11eb-8271-c9a2b0813e40.png)
Hits isn't visible on the character sheet, and is mainly used for integration with modules that expect a single 'HP' value. (Combat Numbers, Health Estimae, etc), or to show on the token bars.

**Comment by edzillion** [comment]
Hey this has been added since 0.8.0 - should work in latest (0.8.4), can you test and report back?

**Comment by xdy** [comment]
Yep, works fine, thank you!
