### ISSUE TITLE
Bleeding at any percent health

### ISSUE THREAD

**Issue by Avitale34** [edzillion/blood-n-guts#187]
Even with the house hold rule of bleeding at 50% checked tokens seem to bleed after they have received any damage. I tried to change the threshold in the advanced configuration but that did nothing as well.

**Comment by edzillion** [comment]
Thanks for the report. What system are you using @Avitale34 ?

**Comment by Avitale34** [comment]
DND 5e

**Comment by ddrecommend** [comment]
@edzillion Seeing the same here. It looks like it's triggering at 15/112 HP, or below 14%. I changed my Actor's HP to 14/100 and it didn't trigger, then changed it to 13/100 and it did not trigger. Very odd, can't nail it down. Happy to help do testing.

**Comment by edzillion** [comment]
I have made a major overhaul to the way Blood n Guts works, and during that I noticed a bug with the damage calculation stuff. I am hoping it fixes this issue.

Can you test v0.8.0 and report back?

**Comment by edzillion** [comment]
Closing as no response.

**Comment by kspear** [comment]
I'm on 0.7.9 and seeing this issue-- is the best fix to update to 0.8.x?
