### ISSUE TITLE
needs optimisation players are getting low frame rates by as much as 10 to 20 frames just from this module

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [edzillion/blood-n-guts#188]
i love your module and i love the intelligent blood colour detection but my players cant use it due to varying degrees of competent pcs. as it standars this is one of the big causes for fps drolps making games harder to play for them. is there anything you could do to optomise this so i can use your module? id really appreciate it.

**Comment by edzillion** [comment]
No worries, I am sure it can be improved, all clients can set the `violence level` independently

https://github.com/edzillion/blood-n-guts#performance--clearing-blood

**Comment by edzillion** [comment]
No reply so closing this.
