### ISSUE TITLE
Request: Universal system support by allowing us to determine which sheet value controls bleeding.

### ISSUE THREAD

**Issue by Vaugher** [edzillion/blood-n-guts#189]
When editing tokens we are able to tie any sheet characteristic we want to the resource bars, would such a thing be possible for the bleeding system as well? This would allow any system to make use of this wonderful mod without painstakingly crafting support for each one. 

Since bleeding is tied to a % of whatever value it is using, this should work no matter which characteristic we decide to tie to bleeding. It might mean we'd have to select the bleeding characteristic for every token we make, but that's honestly not a big deal IMO.

**Comment by edzillion** [comment]
Good idea, and one I hadn't really considered. I will try to implement this now.

**Comment by duskfyre** [comment]
I agree with this one! I'd love to make this work for Lancer (mechs bleeding oil!) and other smaller systems

**Comment by MarlQ** [comment]
Yeah, I'd love this as well.

**Comment by MarlQ** [comment]
So, I just delved into the code and replaced all occurences of `attributes `and `hp `respecively with my system's health variables, and deactivated blood colour... and it... just works.

**Comment by dmrickey** [comment]
Any update on this?

**Comment by edzillion** [comment]
Yep @dmrickey this has been added in v0.8.0 (#207) can you test and report back?

Note: You need to set a tracked attribute for each actor type individually (character, npc etc.). Go to token config on that actor type, then go to the Image tab, then scroll to the bottom, check 'Custom Blood Settings' and then at the bottom there is a field called 'Trackable Health Attribute'.

**Comment by edzillion** [comment]
Closing as no response.
