### ISSUE TITLE
[5e] Blood not appearing for all players

### ISSUE THREAD

**Issue by LastElf** [edzillion/blood-n-guts#191]
Currently on BnG 0.7.5
Everyone is on Kobold (Though the screenshots are after a bit of playing around) but the DM and ex-assist GM (Now a player) can both see it properly. Player blood is bleeding properly but enemy feels like it's 1-10% of the blood it should be (We did around 120 damage to that thing, it should be more than a puddle). Screenshots taken at the same time.

Players:
![image](https://user-images.githubusercontent.com/6188342/105697840-cb6ef100-5f50-11eb-9bc3-8b2913750241.png)

GM:
![image](https://user-images.githubusercontent.com/6188342/105697951-f6f1db80-5f50-11eb-9364-e13e4f3bcb99.png)

This is with a mix of Brave/Chrome/OperaGX as browsers. Can't see anything in the console from the mod. I haven't had a chance to do any testing with player permissions which is my immediate assumption. I can do more testing if you need it to reproduce though.

**Comment by edzillion** [comment]
Not sure why this happened but I have made a major overhaul to the way Blood n Guts works, and I am hoping it fixes this issue.

Can you test v0.8.0 and report back?

**Comment by edzillion** [comment]
Closing as no response
