### ISSUE TITLE
[Request]Cyberpunk RED

### ISSUE THREAD

**Issue by Wilduu** [edzillion/blood-n-guts#193]
Support for [FVTT Cyberpunk RED - Core](https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core) and [Gerdofal](https://github.com/Gerdofal/roll20-CyberpunkRED_Gerdofal_BETA)

Both are Cyberpunk RED systems.

Thanks!

**Comment by edzillion** [comment]
Support for this system was added in latest (v0.8.0) can you test and report back?

**Comment by edzillion** [comment]
Closing as no response.
