### ISSUE TITLE
[Request] Make blood activatable with any trackable stat

### ISSUE THREAD

**Issue by Naturalien** [edzillion/blood-n-guts#194]
It would make it includable in almost all systems easily by being able which track it triggers on. In shadowrun you could just tie it to track.physical, for example. As soon as this bar increases or decreases (maybe a choice?) it would get a trigger for blood.

![2021-02-07 01_45_21-Window](https://user-images.githubusercontent.com/50808821/107133228-37087500-68e6-11eb-9b4e-aecd99c69293.png)

**Comment by edzillion** [comment]
Thanks for the suggestion. I looked into doing something like that, and ran into some issues supporting many different systems. In the end I decided to just go ahead and implement support directly. 

So I was working though the `shadowrun5e` system and I ran into an issue I can't figure out. Do `spirits` have hp? how is combat with them dealt with? Do they have a hp equivalent?

**Comment by edzillion** [comment]
this has been added in v0.8.0 (#207) can you test and report back?

Note: You need to set a tracked attribute for each actor type individually (character, npc etc.). Go to token config on that actor type, then go to the Image tab, then scroll to the bottom, check 'Custom Blood Settings' and then at the bottom there is a field called 'Trackable Health Attribute'.

**Comment by Naturalien** [comment]
> Thanks for the suggestion. I looked into doing something like that, and ran into some issues supporting many different systems. In the end I decided to just go ahead and implement support directly.
> 
> So I was working though the `shadowrun5e` system and I ran into an issue I can't figure out. Do `sprites` have hp? how is combat with them dealt with? Do they have a hp equivalent?

I am very sorry that I did see it only until now.
All beings (fleshy, spirit or vehicle/drone) work the same way. All have a physical damage track which is the amount of damage you can take. But here some differences start. Fleshies and Spirits do have a physical AND a stun track. Vehicles ONLY have a stun track.
- Fleshies: Unconcious when stun track is full. Dying when physical track is full.
- Spirits: Go poof and get disrupted when EITHER of their tracks is full.
- Vehicles: Ignore stun damage completely due to not having a track for it and being broken when their physical track is full.

> this has been added in v0.8.0 (#207) can you test and report back?
> 
> Note: You need to set a tracked attribute for each actor type individually (character, npc etc.). Go to token config on that actor type, then go to the Image tab, then scroll to the bottom, check 'Custom Blood Settings' and then at the bottom there is a field called 'Trackable Health Attribute'.

I will check it as soon as possible!

**Comment by edzillion** [comment]
Closing this as no response from user
