### ISSUE TITLE
[REQUEST] Blood n Guts working for 3.5E SRD by Rughalt

### ISSUE THREAD

**Issue by Grummore** [edzillion/blood-n-guts#196]
Greetings,

I am not Rughalt (obviously), but I would find it very useful and "flavorful" for my campaign!

Thanks for supporting it, if possible.

**Comment by edzillion** [comment]
Support for this system has been added in latest (v0.8.0), can you test and report back?

**Comment by edzillion** [comment]
Closing as no response.
