### ISSUE TITLE
need a feature for having no blood when not visible. 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [edzillion/blood-n-guts#197]
hey so i used your module with some creatures that didnt have their full health that i wanted to bring in but because of your module it wasnt a suprise because it would be dragging the blood pattern behind them. could you make it so that when a creature is invisible or has visibility turned off that it doesnt drag blood spatter. i cant think of a good reason not to have this. it will make your module more usable for gms. 

many thanks.

**Comment by edzillion** [comment]
Yes very good point thanks for the report. Now when a token is hidden it will also be disabled, this works when changing visibility with the hud or alt-dragging onto the scene.  (in v0.8.0 which I am about to release).

The invisibility condition should work too as long as it updates the hidden property of the token (or the GM does manually I guess.)

**Comment by edzillion** [comment]
Actually, I changed this somewhat. Now blood will appear on a hidden token (only visible to GM) but will not drop blood on the floor (which would be visible to anyone). I think this is more intuitive.
