### ISSUE TITLE
[REQUEST] Support for Dungeon Crawl Classics and/or Lamentations of the Flame Princess

### ISSUE THREAD

**Issue by ScorchedInk** [edzillion/blood-n-guts#198]
These are niche systems, but as a retroclone, they are compartively simple in design and hopefully potential options compared to 5E/Pathfinder, and the blood and guts would REALLY fit their world theme.

Thanks for your work! Really awesome!

**Comment by edzillion** [comment]
Support for both these systems has been added in latest (v0.8.0), can you test and report back?

**Comment by edzillion** [comment]
Closing as no response.
