### ISSUE TITLE
Bug: Players seeing blood trail when they shouldn't

### ISSUE THREAD

**Issue by nulmas** [edzillion/blood-n-guts#215]
If the blood layer is off, new players joining the game will see it while the DM doesn't turn it back on and off again. The same happens if a player reloads the browser window.

This wouldn't be a problem in most cases, but the DM may sometimes be expecting the players to decide roll a Survival Check to find a blood trail and this issue might tip them off.

**Comment by Raiu1994** [comment]
Encountered this one as well. We entered a scene with vision set up, and we could see all of the blood, even the stuff that our tokens couldn't see. Apparently it doesn't work correctly with visibility on the most recent build. This persisted even when the DM turned the blood layer off and on again.
