### ISSUE TITLE
Getting a canvas drawing error during scene loading

### ISSUE THREAD

**Issue by luizbgomide** [edzillion/blood-n-guts#225]
![image](https://user-images.githubusercontent.com/18707781/110987231-8d395f80-834d-11eb-84e2-6d3ce76397ac.png)

![image](https://user-images.githubusercontent.com/18707781/110987302-a6daa700-834d-11eb-89d8-ae0f1a246c1f.png)

**Comment by edzillion** [comment]
A little more info would help. 
Have you tried running blood and guts on it's own? Is this a scene that has blood on it already? Can you try wiping the blood in the scene and reloading?

**Comment by luizbgomide** [comment]
It is a scene that had blood, but I already wipe all of it. But it seems to be hit and miss. Some scenes shows that error and others do not. This only appears when the scene is set as Activated and I first load the World.

If I load the World in a scene that works without error, and the Activate one of the scenes that usually produce an error, it doesn't show anymore.

I used Find the Culprit with just Blood 'n Guts and got this:
![image](https://user-images.githubusercontent.com/18707781/110992306-819d6700-8354-11eb-9f3b-f988457a3d7e.png)

**Comment by edzillion** [comment]
Thanks that helps. What system and blood-n-guts versions are you running?

**Comment by luizbgomide** [comment]
Latest Blood and Guts and PF2, just update today and both had updates.

**Comment by edzillion** [comment]
OK I had a look and I think I have an idea. Can you rename this file to remove the `.txt` part and then replace the the same file in the Blood n Guts module.

On windows it's in `\foundry-data\Data\modules\blood-n-guts\`

I am hoping that fixes the problem but could you also copy the console logs where it says 'token draw missing actor for token'? thanks

[blood-n-guts.ts.txt](https://github.com/edzillion/blood-n-guts/files/6133736/blood-n-guts.ts.txt)

**Comment by luizbgomide** [comment]
Hey, do you mind transpiling it to JS, I don't have TypeScript setup at my PC :D

**Comment by edzillion** [comment]
yeah sorry just came back here cos I realised that :) 
[blood-n-guts.js.txt](https://github.com/edzillion/blood-n-guts/files/6133761/blood-n-guts.js.txt)

**Comment by luizbgomide** [comment]
Yep. that fixed.

`blood-n-guts |  token draw missing actor for token Tesouro`

"Tesouro" is my loot actor, and if I'm not mistaken I removed the original actor and created a new one, which means that indeed this token is actorless...

**Comment by luizbgomide** [comment]
Thanks a lot for the support and the amazing module :D
