### ISSUE TITLE
Death blows are not handled properly.

### ISSUE THREAD

**Issue by kimitsu** [edzillion/blood-n-guts#244]
When the modified hp reaches zero the following line would ignore that value and the consequent damage severity calculations would be based on the unmodified hp, resulting in no blood at all.
```
SplatToken.js@214:
        const currentHP = BloodNGuts.system.currentHPChange(changes, this.actorType) ||
            BloodNGuts.system.currentHP(this.token, this.actorType);
```

**Comment by edzillion** [comment]
You're right of course. Thanks. This fix will be in the upcoming v0.8.7 release
