### ISSUE TITLE
Feature Request: Macro to clean screen 

### ISSUE THREAD

**Issue by radkonf** [edzillion/blood-n-guts#256]
I know I can clean the screen via Settings macro setting BnG Advanced Settings Wipe Screen 
But thats way to long 
a Macro would be awesome

**Comment by edzillion** [comment]
You can do that. just type '/blood clear' into chat

https://github.com/edzillion/blood-n-guts#performance--clearing-blood

**Comment by radkonf** [comment]
Nice that helps. 
Next time I scroll all the way down :)
