### ISSUE TITLE
[feature request] About face compatibility

### ISSUE THREAD

**Issue by Ecatombe86** [edzillion/blood-n-guts#48]
I found out that the blood trail function makes the token stand still even though I have About face installed (module that rotate the tokens based on the last input direction)

**Comment by edzillion** [comment]
Yeah, I noticed that it wasn't playing well together and I agree it's really important. I made a PR on that repo but it's hard to tell what should be done because it seems there is a lot of redundant code so it's hard to tell what's going on.

https://github.com/eadorin/about-face/pull/34

**Comment by edzillion** [comment]
Ok @Ecatombe86 this is fixed in latest `about-face` (version number is the same but you can still `update`)
