### ISSUE TITLE
Please add support for Pathfinder 2nd Edition

### ISSUE THREAD

**Issue by apoapostolov** [edzillion/blood-n-guts#77]
This is solely needed as this mod is pretty system-agnostic in its functionality, it just needs to recognize the health values of more systems. Perhaps the value to watch should be exposed in the Settings.

**Comment by edzillion** [comment]
Hey thanks for the contribution @apoapostolov - do you have any prebuilt characters, monsters etc that I can test against? If you had a populated p2fe world that I could play that would be perfect. I don't have any experience with pathfinder

**Comment by apoapostolov** [comment]
Yes. Here it is. https://we.tl/t-8RjqMX4LY1

**Comment by edzillion** [comment]
Basic support added in #82
